version: '2.2'

networks:
  pcp-bridge-network:
    external: true

services:

  # ros-master:
  #   image: ros:noetic-ros-core
  #   container_name: ros-master
  #   command: stdbuf -o L roscore
  #   networks:
  #     pcp-bridge-network:
  #       ipv4_address: 192.168.56.2
  #   environment:
  #     - "ROS_MASTER_URI=http://192.168.56.2:11311"
  #     - "ROS_HOSTNAME=192.168.56.2"
  #   restart: always

  rosbridge-suite:
    image: aictrobotics/rosbridge-ros2:latest
    container_name: rosbridge-suite
    command: >
      bash -c "ros2 launch rosbridge_server rosbridge_websocket_launch.xml"
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.3
    ports:
      - "9090:9090"
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.3"
    restart: always

  simulator:
    image: aictrobotics/turtlebot3-ros2:latest
    container_name: simulator
    # depends_on:
    #   - ros-master
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.4
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.4"
      # - "DISPLAY=unix$DISPLAY"
      - "DISPLAY=host.docker.internal:0.0"
      - "LIBGL_ALWAYS_INDIRECT=0"
      # network_mode: "host"
    # volumes: 
    #   - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "source ~/dev_ws/install/setup.bash && export TURTLEBOT3_MODEL=burger && ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py"
    privileged: true
    restart: always

  slam:
    image: aictrobotics/turtlebot3-ros2:latest
    container_name: slam
    # depends_on:
    #   - ros-master
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.6
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.6"
      # - "DISPLAY=unix$DISPLAY"
      - "DISPLAY=host.docker.internal:0.0"
      - "LIBGL_ALWAYS_INDIRECT=0"
      # network_mode: "host"
    # volumes: 
    #   - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "source ~/dev_ws/install/setup.bash && export TURTLEBOT3_MODEL=burger && ros2 launch turtlebot3_cartographer cartographer.launch.py use_sim_time:=True"
    privileged: true
    restart: always

  foxglove:
    image: ghcr.io/foxglove/studio:latest
    container_name: foxglove
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.5
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.5"
    ports:
      - "172.30.1.50:8081:8080" # you should port forwarding with ip of your computer. and if it's not working, change port of local.
    privileged: true
    restart: always
